### ISSUE TITLE
authorize_access_token breaks when request has extra query/path parameter

### ISSUE THREAD

**Issue by rupansh** [lepture/authlib#252] opened 2020-07-14 09:15 UTC
**Describe the bug**
I am using starlette integration with fastapi
In my auth endpoint I have another query parameter in my url called username which I am taking from the login endpoint
i.e
login endpoint:
```
    redirect = f"{req.url_for('github_auth')}/?username={req.query_params['username']}"
    return await oauth.github.authorize_redirect(req, redirect)
```

auth endpoint:
```
    token = await oauth.github.authorize_access_token(req)
```

However this causes an error in httpx. 
It doesn't happen when username is not passed.
Path parameter isn't working either!
```
    redirect = req.url_for("github_auth", username=req.query_params["username"])
```

```
@router.get("/github/auth/{username}/")
async def github_auth(username: str, request: Request)
```

**Error Stacks**

```
Traceback (most recent call last):
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/fastapi/applications.py", line 181, in __call__
    await super().__call__(scope, receive, send)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/fastapi/routing.py", line 196, in app
    raw_response = await run_endpoint_function(
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/fastapi/routing.py", line 147, in run_endpoint_function
    return await dependant.call(**values)
  File "./routers/oauth.py", line 40, in github_auth
    await oauth.github.authorize_access_token(request)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/authlib/integrations/starlette_client/integration.py", line 58, in authorize_access_token
    return await self.fetch_access_token(**params)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/authlib/integrations/base_client/async_app.py", line 105, in fetch_access_token
    token = await client.fetch_token(token_endpoint, **kwargs)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 103, in _fetch_token
    resp = await self.post(
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/httpx/_client.py", line 1374, in post
    return await self.request(
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 84, in request
    return await super(AsyncOAuth2Client, self).request(
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/httpx/_client.py", line 1137, in request
    request = self.build_request(
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/httpx/_client.py", line 194, in build_request
    url = self.merge_url(url)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/httpx/_client.py", line 214, in merge_url
    url = self.base_url.join(relative_url=url)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/httpx/_models.py", line 222, in join
    return URL(relative_url)
  File "/home/rupansh/PycharmProjects/bruh-project2/venv/lib/python3.8/site-packages/httpx/_models.py", line 71, in __init__
    self._uri_reference = url._uri_reference
AttributeError: 'NoneType' object has no attribute '_uri_reference'

```

**To Reproduce**

```
from authlib.integrations.starlette_client import OAuth
from fastapi import APIRouter, Request, HTTPException

router = APIRouter()
oauth = OAuth()
oauth.register(name="github", ...)

@router.route("/github")
async def github_login(req: Request):
    if not ("username" in req.query_params.keys() and req.query_params["username"]):
        raise HTTPException(status_code=400, detail="invalid_username")
    redirect = req.url_for("github_auth", username=req.query_params["username"])
    return await oauth.github.authorize_redirect(req, redirect)

@router.route("/github/auth")
async def github_auth(request: Request):
    if not ("username" in request.query_params.keys() and request.query_params["username"]):
        raise HTTPException(status_code=400, detail="invalid_username")

    token = await oauth.github.authorize_access_token(request)
    # do stuff with token
```

**Expected behavior**

The server shouldn't error out at `token = await oauth.github.authorize_access_token(request)`

**Environment:**

 - OS: Linux (5.7.7)
 - Python Version: 3.8
 - Authlib Version: 0.14.3

**Comment by lepture** [comment] 2020-07-15 14:48
@rupansh I can't reproduce it. And you have certain errors in your code:

For query string in your **To Reproduce** code:

```python
redirect = req.url_for("github_auth", username=req.query_params["username"])
```

This will raise error.

For your code:

```python
@router.get("/github/auth/{username}/")
async def github_auth(username: str, request: Request)
```

This is not correct either, it should be:

```python
@router.get("/github/auth/{username}/")
async def github_auth(request: Request)
```

Because, the `request` model is defined as `Request`.

---

And I have tested for query string and route path myself, it works well. I'll close this issue, because it is invalid.

If you still encounter the problem, you can reopen it. And it would be helpful if you can create a repo like one in https://github.com/authlib/demo-oauth-client so that I can test it again.

**Closed by lepture** 2020-07-15 14:48 UTC
Labels: invalid
