### ISSUE TITLE
Auth required after fetch_token with AsyncOAuth2Client

### ISSUE THREAD

**Issue by elijahsgh** [lepture/authlib#379] opened 2021-08-27 04:34 UTC
**Describe the bug**

Documentation shows client.get, .post, etc being used immediately after client.fetch_token() but this does not seem to work.

**To Reproduce**
```
from authlib.integrations.httpx_client.oauth2_client import OAuth2Client, OAuth2Auth
oauth_client = AsyncOAuth2Client(...)

token = await oauth_client.fetch_token(
  API_TOKEN_URL,
  authorization_response=str(request.url),
  grant_type='authorization_code',
)

user_request = await oauth_client.get(API_URL + "/users")
```
_**401 here**_

However, if you use:
```
user_request = await oauth_client.get(API_URL + "/users", auth=OAuth2Auth(client.token))
... or ...

client.auth = OAuth2Auth(client.token)
user_request = await oauth_client.get(API_URL + "/users")

```
_**200 here**_

**Expected behavior**

As per the docs suggest, I should be able to use .get, .post, etc immediately after using fetch_token() or maybe the docs should be updated for the methods above? I don't know how it's supposed to work. The docs make it seem like I should be able to use .get immediately against an endpoint requiring authentication.

**Environment:**

 - OS: Linux
 - Python Version: 3.9.6
 - Authlib Version: 0.15.4

**Comment by twelvelabs** [comment] 2021-09-09 21:11
Dupe of #377

**Comment by elijahsgh** [comment] 2021-09-09 21:27
Is this a dupe, @twelvelabs ? I reviewed that and while the workaround technically works there is a much easier work around above involving just assigning the .auth member.

It does work and I don't have to set the header unless assigning .auth sets a header?

I don't believe this is the same issue.

**Comment by twelvelabs** [comment] 2021-09-09 21:37
Both issues are caused by the same underlying problem (see [this comment](https://github.com/lepture/authlib/issues/377#issuecomment-916445792)) - a version incompatibility between newer versions of httpx and authlib.

**Closed as completed** 2021-10-18 12:16 UTC
