### ISSUE TITLE
Decoding a JWS token with ES256 doesn't work

### ISSUE THREAD

**Issue by fenix01** [lepture/authlib#176] opened 2019-12-30 09:39 UTC
**Describe the bug**

Hi!
I'm trying to implement an OAuth2 server with authlib and I found a bug in the library with ES256. I was trying to decode a JWS token signed with ES256 but the library has raised an exception.
The generation of a JWT with ES256 works, but not the decoding.

Here it's the small piece of code that raises an exception :

```
def gen_refresh_token(self, client, grant_type, user, scope):
        jws = JsonWebSignature(algorithms=JWS_ALGORITHMS)
        header = {'alg': 'ES256'}
        date = datetime.utcnow()
        payload = {
            'client_id': client.get_client_id(),
            'iat': int(date.timestamp()),
            'user_id': user["id"],
            'scope': scope,
            'exp': 604800
        }
        try:
            key = open("my_ec_key.pem", 'r').read()
            s = jws.serialize_compact(header, json.dumps(payload), key)
        except Exception as e:
            logger.exception('JWS exception', e)
        return s.decode("utf-8")
...

class RefreshTokenGrant(grants.RefreshTokenGrant):
    INCLUDE_NEW_REFRESH_TOKEN = True

    def authenticate_refresh_token(self, refresh_token):
        jws = JsonWebSignature(algorithms=JWS_ALGORITHMS)
        try:
            key = open("my_ec_pub.pem", 'r').read()
            jws_obj = jws.deserialize_compact(refresh_token, key)
            ...
        except Exception as e:
            logger.exception('JWS exception', e)
```

And the traceback :
```
Traceback (most recent call last):
  File "/mnt/d/documents/exo1/src/exo1/rest/flask/oauth2.py", line 64, in authenticate_refresh_token
    jws_obj = jws.deserialize_compact(refresh_token, key)
  File "/home/yohann/.local/lib/python3.6/site-packages/authlib/jose/rfc7515/jws.py", line 115, in deserialize_compact
    self._algorithms, jws_header, payload, key)
  File "/home/yohann/.local/lib/python3.6/site-packages/authlib/jose/util.py", line 14, in prepare_algorithm_key
    key = algorithm.prepare_public_key(key)
  File "/home/yohann/.local/lib/python3.6/site-packages/authlib/jose/rfc7518/_backends/_key_cryptography.py", line 42, in prepare_public_key
    if key.startswith(b'ecdsa-sha2-'):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

**To Reproduce**

I put a small example of the code above.

**Expected behavior**

I should get the content of the token.

**Environment:**

 - OS: Windows Subsystem for Linux
 - Python Version: 3.6.8
 - Authlib Version: 0.13.0

**Additional context**

I found a patch for my use case. You have to edit the file in :
authlib/jose/rfc7518/_backends/_key_cryptography.py

In the class ECKey, the method prepare_public_key doesn't convert the key to bytes. I did the following patch :

```
def prepare_public_key(self, key):
        if isinstance(key, EllipticCurvePublicKey):
            return key
        key = to_bytes(key)
        if key.startswith(b'ecdsa-sha2-'):
            return load_ssh_public_key(key, backend=default_backend())
        else:
            return load_pem_public_key(key, backend=default_backend())
```

**Comment by lepture** [comment] 2020-01-01 12:21
Hi, can you test this code with your Python interpreter:

```python
>>> s = b'hello'
>>> s.startswith(b'h')
```

I can't reproduce your problem.

**Comment by fenix01** [comment] 2020-01-01 13:35
Hi,

Your code returns true in my python interpreter but the bug is different. In your example, s should be a string.
And in that case, you have the following exception :
`TypeError: startswith first arg must be str or a tuple of str, not bytes`

When I call deserialize_compact my public key is loaded in ASCII mode, and startswith failed because the key is not converted with to_bytes.

In serialize_compact, my private key is loaded in ASCII mode, but the key is converted afterwards in bytes. So it works correctly.

**Comment by lepture** [comment] 2020-01-02 07:52
Ok, I got it. Your code should be:

```python
    key = open("./etc/oauth_ec_key.pem", 'rb').read()
    s = jws.serialize_compact(header, json.dumps(payload), key)
```

You need to `open` with **`rb`**.

**Comment by fenix01** [comment] 2020-01-02 15:30
You're right, but I'm not sure it's the best solution because in the example serialize_compact works with "r" mode.

To resume:
- serialize_compact works with "r" mode
- deserialize_compact doesn't work with "r" mode

For me, both functions should work with "r" mode, not only one of them.

**Comment by lepture** [comment] 2020-02-11 11:00
fixed in master

**Closed by lepture** 2020-02-11 11:00 UTC
Labels: bug
